#!/bin/bash

echo $REQ_TOCKEN;
echo $USER_R;
echo $PASSW;

curl 'https://my.rozetka.com.ua/cgi-bin/form.php?r=https%3A%2F%2Fmy.rozetka.com.ua%2Fsignin%2F&action=SignIn' \
-H 'ajaxAction: https://my.rozetka.com.ua/signin/#SignIn' \
-H "Cookie: uid=$REQ_TOCKEN;" \
--data "login=$USER_R&password=$PASSW&request_token=$REQ_TOCKEN" \
--compressed \
-c tmp/autorize_cookie

