#!/bin/bash
curl 'https://my.rozetka.com.ua/cgi-bin/form.php?r=https%3A%2F%2Fmy.rozetka.com.ua%2Fsignin%2F&action=SignIn' \
-H 'ajaxAction: https://my.rozetka.com.ua/signin/#SignIn' \
-H 'Cookie: uid===;' \
-H 'x-request-token: ' \
--data 'login=&password=&request_token=%3D%3D' \
--compressed \
-c tmp/autorize_cookie.txt

